const t = {
  en: {
    navTitle: '🎮 Games & Tools',
    backToResume: '← Resume',
    heroTitle: 'Welcome to my play corner ✨',
    heroSubtitle: 'Casual games and handy everyday tools',
    games: 'Games',
    tools: 'Tools',
    back: '← Back',
    restart: 'Restart',
    // 2048
    won2048: '🎉 You got 2048!',
    continueGame: 'Keep Going',
    gameOver: 'Game Over',
    hint2048: 'Arrow keys / swipe to move',
    // Snake
    snakeTitle: 'Snake',
    pressToStart: 'Press an arrow key to start',
    paused: 'Paused',
    resume: 'Resume',
    scoreLabel: 'Score: ',
    hintSnake: 'Arrow keys / WASD / swipe  ·  Space to pause',
    // Wordle
    wordleTitle: 'Wordle',
    wordleNew: 'New',
    wordleEnter: 'Enter',
    wordleNotEnough: 'Not enough letters',
    wordleInvalidWord: 'Not a valid word',
    wordleWon: n => n === 1 ? 'Genius! First try!' : `Solved in ${n}!`,
    wordleLost: ans => `The word was ${ans}`,
    wordleShare: 'Share',
    wordleCopied: 'Copied!',
    hintWordle: 'Type or tap · Enter to submit · Backspace to delete',
    // Reaction Test
    reactionTitle: 'Reaction Test',
    reactionClickToStart: 'Click to Begin',
    reactionIdleHint: 'tap the box to start',
    reactionWaiting: 'Wait...',
    reactionWaitingHint: 'don\'t click yet',
    reactionGo: 'Click!',
    reactionTooEarly: 'Too early!',
    reactionTryAgain: 'tap to try again',
    reactionMs: ms => `${ms} ms`,
    reactionAgainHint: 'tap to go again',
    reactionBest: 'Best',
    reactionAvg: 'Avg',
    reactionAttempts: 'Tries',
    hintReaction: 'Click or tap the box the instant it turns green',
    // Typing game
    typingTitle:    'Falling Words',
    typingSubtitle: 'Words fall from the top — type them before they reach the ground. Speed and length increase as your score grows.',
    typingStart:    'Start',
    typingRetry:    'Try Again',
    typingScore:    'Score',
    typingHint:     'Type the falling words · Backspace to retry a letter · Esc to unlock target',
    // Hue Sorter
    hueTitle:    'Hue Sorter',
    hueHint:     'Drag the swatches into the correct gradient order',
    hueLockNote: '◀ first and last colours are fixed ▶',
    hueMoves:    'Moves ',
    hueTime:     'Time ',
    hueSolved:   'Perfect gradient!',
    hueSolvedSub: (moves, time) => `${moves} moves · ${time}`,
    hueRetry:    'Retry',
    hueNext:     'Next Palette',
    // Ambient Mixer
    ambientTitle: 'Ambient Mixer',
    ambientMaster: 'Master',
    ambientPlay: 'Play',
    ambientStop: 'Stop',
    ambientHint: 'Toggle sounds above to start mixing',
    ambientSounds: {
      rain:  { label: 'Rain',        emoji: '🌧️' },
      ocean: { label: 'Ocean',       emoji: '🌊' },
      wind:  { label: 'Wind',        emoji: '🌬️' },
      fire:  { label: 'Fire',        emoji: '🔥' },
      white: { label: 'White Noise', emoji: '📻' },
    },
    // Notepad
    notepadTitle: 'Notepad',
    notepadClear: 'Clear',
    notepadConfirmClear: 'Confirm?',
    notepadStatus: (n) => `Auto-saved · ${n} chars`,
    notepadPlaceholder: 'Start typing…',
    // Spinner
    spinnerTitle: 'Spinner',
    spinning: 'Spinning…',
    spinStart: 'Spin',
    optionList: (n) => `Options (${n})`,
    addOption: '+ Add',
    optionPlaceholder: 'Option name',
    congrats: 'Winner!',
    spinAgain: 'Spin Again',
    // App cards
    apps: {
      '2048':       { title: '2048',       desc: 'Merge tiles, chase the 2048 square.' },
      snake:        { title: 'Snake',       desc: 'Classic snake — eat more, move faster.' },
      wordle:       { title: 'Wordle',       desc: 'Guess the daily 5-letter word in 6 tries.' },
      reaction:     { title: 'Reaction',    desc: 'Test your reflexes in milliseconds.' },
      typing:       { title: 'Falling Words', desc: 'Type falling words before they hit the ground.' },
      hue:          { title: 'Hue Sorter',   desc: 'Drag colour swatches into the perfect gradient.' },
      ambient:      { title: 'Ambient',     desc: 'Mix background sounds for deep focus.' },
      notepad:      { title: 'Notepad',     desc: 'Quick notes, auto-saved locally.' },
      calendar:     { title: 'Calendar',    desc: 'Browse months and reminders.' },
      calculator:   { title: 'Calculator',  desc: 'A clean everyday calculator.' },
      spinner:      { title: 'Spinner',     desc: 'Add options, spin the wheel!' },
      tba:          { title: 'TBA',         desc: 'Task board with Eisenhower matrix prioritization.' },
    },
  },
  zh: {
    navTitle: '🎮 小游戏与工具',
    backToResume: '← 简历',
    heroTitle: '欢迎来到我的小站 🎉',
    heroSubtitle: '这里有休闲小游戏和实用的日常工具，随取随用',
    games: '游戏',
    tools: '工具',
    back: '← 返回',
    restart: '重新开始',
    // 2048
    won2048: '🎉 达成 2048！',
    continueGame: '继续游戏',
    gameOver: '游戏结束',
    hint2048: '方向键 / 滑动 来操作',
    // Snake
    snakeTitle: '贪吃蛇',
    pressToStart: '按方向键开始游戏',
    paused: '已暂停',
    resume: '继续',
    scoreLabel: '得分：',
    hintSnake: '方向键 / WASD / 滑动 来操作  ·  空格暂停',
    // Wordle
    wordleTitle: 'Wordle',
    wordleNew: '新游戏',
    wordleEnter: '确认',
    wordleNotEnough: '字母不够',
    wordleInvalidWord: '不是有效单词',
    wordleWon: n => n === 1 ? '天才！一次猜中！' : `${n} 次猜中！`,
    wordleLost: ans => `答案是 ${ans}`,
    wordleShare: '分享结果',
    wordleCopied: '已复制！',
    hintWordle: '输入或点击字母 · 确认键提交 · 退格键删除',
    // Reaction Test
    reactionTitle: '反应力测试',
    reactionClickToStart: '点击开始',
    reactionIdleHint: '点击方框开始',
    reactionWaiting: '等待...',
    reactionWaitingHint: '还没到时候',
    reactionGo: '点击！',
    reactionTooEarly: '抢跑了！',
    reactionTryAgain: '点击重试',
    reactionMs: ms => `${ms} 毫秒`,
    reactionAgainHint: '点击再来一次',
    reactionBest: '最佳',
    reactionAvg: '平均',
    reactionAttempts: '次数',
    hintReaction: '方框变绿的瞬间点击',
    // Typing game
    typingTitle:    '打字防御战',
    typingSubtitle: '单词从顶部落下——在它们到达底部之前打出来。得分越高，单词越长，下落越快。',
    typingStart:    '开始',
    typingRetry:    '再来一次',
    typingScore:    '得分',
    typingHint:     '打出下落的单词 · 退格键撤销一个字母 · Esc 解除锁定',
    // Hue Sorter
    hueTitle:    '色感排序',
    hueHint:     '拖拽色块，将它们排列成平滑的渐变顺序',
    hueLockNote: '◀ 首尾色块已固定 ▶',
    hueMoves:    '步数 ',
    hueTime:     '用时 ',
    hueSolved:   '渐变完美！',
    hueSolvedSub: (moves, time) => `${moves} 步 · ${time}`,
    hueRetry:    '重试',
    hueNext:     '换配色',
    // Ambient Mixer
    ambientTitle: '白噪音混音器',
    ambientMaster: '主音量',
    ambientPlay: '播放',
    ambientStop: '停止',
    ambientHint: '点击上方按钮开启声音',
    ambientSounds: {
      rain:  { label: '雨声',   emoji: '🌧️' },
      ocean: { label: '海浪',   emoji: '🌊' },
      wind:  { label: '风声',   emoji: '🌬️' },
      fire:  { label: '壁炉',   emoji: '🔥' },
      white: { label: '白噪音', emoji: '📻' },
    },
    // Notepad
    notepadTitle: '记事本',
    notepadClear: '清空',
    notepadConfirmClear: '确认清空？',
    notepadStatus: (n) => `已自动保存 · 共 ${n} 字`,
    notepadPlaceholder: '开始输入...',
    // Spinner
    spinnerTitle: '转盘抽奖',
    spinning: '转动中...',
    spinStart: '开始转动',
    optionList: (n) => `选项列表（${n}）`,
    addOption: '+ 添加',
    optionPlaceholder: '选项名称',
    congrats: '恭喜！',
    spinAgain: '再转一次',
    // App cards
    apps: {
      '2048':       { title: '2048',    desc: '合并数字，挑战 2048！' },
      snake:        { title: '贪吃蛇', desc: '经典贪吃蛇，吃得越多越难' },
      wordle:       { title: 'Wordle',    desc: '6 次机会猜出每日 5 字母单词。' },
      reaction:     { title: '反应力测试', desc: '毫秒级别的反应力挑战。' },
      typing:       { title: '打字防御战', desc: '在单词落地前打出来，速度越来越快。' },
      hue:          { title: '色感排序', desc: '拖动色块，拼出完美的颜色渐变。' },
      ambient:      { title: '白噪音混音器', desc: '混合环境音，帮助专注。' },
      notepad:      { title: '记事本', desc: '随手记，自动保存' },
      calendar:     { title: '日历',   desc: '查看日期与备忘' },
      calculator:   { title: '计算器', desc: '日常计算用' },
      spinner:      { title: '转盘抽奖', desc: '填入选项，转盘决定！' },
      tba:          { title: 'TBA 任务板', desc: '基于艾森豪威尔矩阵的任务管理系统。' },
    },
  },
}

export default t
